// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	example_com_v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/rabbitmq-operator/pkg/apis/example.com/v1alpha1"
	versioned "github.com/tangfeixiong/go-to-kubernetes/rabbitmq-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tangfeixiong/go-to-kubernetes/rabbitmq-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/rabbitmq-operator/pkg/client/listers/example.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AmqpInformer provides access to a shared informer and lister for
// Amqps.
type AmqpInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AmqpLister
}

type amqpInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAmqpInformer constructs a new informer for Amqp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAmqpInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAmqpInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAmqpInformer constructs a new informer for Amqp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAmqpInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().Amqps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().Amqps(namespace).Watch(options)
			},
		},
		&example_com_v1alpha1.Amqp{},
		resyncPeriod,
		indexers,
	)
}

func (f *amqpInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAmqpInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *amqpInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&example_com_v1alpha1.Amqp{}, f.defaultInformer)
}

func (f *amqpInformer) Lister() v1alpha1.AmqpLister {
	return v1alpha1.NewAmqpLister(f.Informer().GetIndexer())
}
