// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/tangfeixiong/go-to-kubernetes/rabbitmq-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Amqps returns a AmqpInformer.
	Amqps() AmqpInformer
	// Rabbitmqs returns a RabbitmqInformer.
	Rabbitmqs() RabbitmqInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Amqps returns a AmqpInformer.
func (v *version) Amqps() AmqpInformer {
	return &amqpInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Rabbitmqs returns a RabbitmqInformer.
func (v *version) Rabbitmqs() RabbitmqInformer {
	return &rabbitmqInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
