// This file was automatically generated by lister-gen

package v1alpha1

// AmqpListerExpansion allows custom methods to be added to
// AmqpLister.
type AmqpListerExpansion interface{}

// AmqpNamespaceListerExpansion allows custom methods to be added to
// AmqpNamespaceLister.
type AmqpNamespaceListerExpansion interface{}

// RabbitmqListerExpansion allows custom methods to be added to
// RabbitmqLister.
type RabbitmqListerExpansion interface{}

// RabbitmqNamespaceListerExpansion allows custom methods to be added to
// RabbitmqNamespaceLister.
type RabbitmqNamespaceListerExpansion interface{}
