// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/tangfeixiong/go-to-kubernetes/mysql-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Mariadbs returns a MariadbInformer.
	Mariadbs() MariadbInformer
	// Mysqls returns a MysqlInformer.
	Mysqls() MysqlInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Mariadbs returns a MariadbInformer.
func (v *version) Mariadbs() MariadbInformer {
	return &mariadbInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Mysqls returns a MysqlInformer.
func (v *version) Mysqls() MysqlInformer {
	return &mysqlInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
