// This file was automatically generated by lister-gen

package v1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// RedisListerExpansion allows custom methods to be added to
// RedisLister.
type RedisListerExpansion interface{}

// RedisNamespaceListerExpansion allows custom methods to be added to
// RedisNamespaceLister.
type RedisNamespaceListerExpansion interface{}
