// This file was automatically generated by lister-gen

package v1alpha1

// MariadbListerExpansion allows custom methods to be added to
// MariadbLister.
type MariadbListerExpansion interface{}

// MariadbNamespaceListerExpansion allows custom methods to be added to
// MariadbNamespaceLister.
type MariadbNamespaceListerExpansion interface{}

// MysqlListerExpansion allows custom methods to be added to
// MysqlLister.
type MysqlListerExpansion interface{}

// MysqlNamespaceListerExpansion allows custom methods to be added to
// MysqlNamespaceLister.
type MysqlNamespaceListerExpansion interface{}
