// This file was automatically generated by lister-gen

package v1alpha1

// HadoopListerExpansion allows custom methods to be added to
// HadoopLister.
type HadoopListerExpansion interface{}

// HadoopNamespaceListerExpansion allows custom methods to be added to
// HadoopNamespaceLister.
type HadoopNamespaceListerExpansion interface{}

// HadoopHdfsListerExpansion allows custom methods to be added to
// HadoopHdfsLister.
type HadoopHdfsListerExpansion interface{}

// HadoopHdfsNamespaceListerExpansion allows custom methods to be added to
// HadoopHdfsNamespaceLister.
type HadoopHdfsNamespaceListerExpansion interface{}

// HadoopMapreduceListerExpansion allows custom methods to be added to
// HadoopMapreduceLister.
type HadoopMapreduceListerExpansion interface{}

// HadoopMapreduceNamespaceListerExpansion allows custom methods to be added to
// HadoopMapreduceNamespaceLister.
type HadoopMapreduceNamespaceListerExpansion interface{}

// HadoopNodeListerExpansion allows custom methods to be added to
// HadoopNodeLister.
type HadoopNodeListerExpansion interface{}

// HadoopNodeNamespaceListerExpansion allows custom methods to be added to
// HadoopNodeNamespaceLister.
type HadoopNodeNamespaceListerExpansion interface{}

// HadoopYarnListerExpansion allows custom methods to be added to
// HadoopYarnLister.
type HadoopYarnListerExpansion interface{}

// HadoopYarnNamespaceListerExpansion allows custom methods to be added to
// HadoopYarnNamespaceLister.
type HadoopYarnNamespaceListerExpansion interface{}
