// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/apis/example.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HadoopHdfsLister helps list HadoopHdfses.
type HadoopHdfsLister interface {
	// List lists all HadoopHdfses in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopHdfs, err error)
	// HadoopHdfses returns an object that can list and get HadoopHdfses.
	HadoopHdfses(namespace string) HadoopHdfsNamespaceLister
	HadoopHdfsListerExpansion
}

// hadoopHdfsLister implements the HadoopHdfsLister interface.
type hadoopHdfsLister struct {
	indexer cache.Indexer
}

// NewHadoopHdfsLister returns a new HadoopHdfsLister.
func NewHadoopHdfsLister(indexer cache.Indexer) HadoopHdfsLister {
	return &hadoopHdfsLister{indexer: indexer}
}

// List lists all HadoopHdfses in the indexer.
func (s *hadoopHdfsLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopHdfs, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopHdfs))
	})
	return ret, err
}

// HadoopHdfses returns an object that can list and get HadoopHdfses.
func (s *hadoopHdfsLister) HadoopHdfses(namespace string) HadoopHdfsNamespaceLister {
	return hadoopHdfsNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HadoopHdfsNamespaceLister helps list and get HadoopHdfses.
type HadoopHdfsNamespaceLister interface {
	// List lists all HadoopHdfses in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopHdfs, err error)
	// Get retrieves the HadoopHdfs from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.HadoopHdfs, error)
	HadoopHdfsNamespaceListerExpansion
}

// hadoopHdfsNamespaceLister implements the HadoopHdfsNamespaceLister
// interface.
type hadoopHdfsNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HadoopHdfses in the indexer for a given namespace.
func (s hadoopHdfsNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopHdfs, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopHdfs))
	})
	return ret, err
}

// Get retrieves the HadoopHdfs from the indexer for a given namespace and name.
func (s hadoopHdfsNamespaceLister) Get(name string) (*v1alpha1.HadoopHdfs, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hadoophdfs"), name)
	}
	return obj.(*v1alpha1.HadoopHdfs), nil
}
