// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/apis/example.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HadoopMapreduceLister helps list HadoopMapreduces.
type HadoopMapreduceLister interface {
	// List lists all HadoopMapreduces in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopMapreduce, err error)
	// HadoopMapreduces returns an object that can list and get HadoopMapreduces.
	HadoopMapreduces(namespace string) HadoopMapreduceNamespaceLister
	HadoopMapreduceListerExpansion
}

// hadoopMapreduceLister implements the HadoopMapreduceLister interface.
type hadoopMapreduceLister struct {
	indexer cache.Indexer
}

// NewHadoopMapreduceLister returns a new HadoopMapreduceLister.
func NewHadoopMapreduceLister(indexer cache.Indexer) HadoopMapreduceLister {
	return &hadoopMapreduceLister{indexer: indexer}
}

// List lists all HadoopMapreduces in the indexer.
func (s *hadoopMapreduceLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopMapreduce, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopMapreduce))
	})
	return ret, err
}

// HadoopMapreduces returns an object that can list and get HadoopMapreduces.
func (s *hadoopMapreduceLister) HadoopMapreduces(namespace string) HadoopMapreduceNamespaceLister {
	return hadoopMapreduceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HadoopMapreduceNamespaceLister helps list and get HadoopMapreduces.
type HadoopMapreduceNamespaceLister interface {
	// List lists all HadoopMapreduces in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopMapreduce, err error)
	// Get retrieves the HadoopMapreduce from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.HadoopMapreduce, error)
	HadoopMapreduceNamespaceListerExpansion
}

// hadoopMapreduceNamespaceLister implements the HadoopMapreduceNamespaceLister
// interface.
type hadoopMapreduceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HadoopMapreduces in the indexer for a given namespace.
func (s hadoopMapreduceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopMapreduce, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopMapreduce))
	})
	return ret, err
}

// Get retrieves the HadoopMapreduce from the indexer for a given namespace and name.
func (s hadoopMapreduceNamespaceLister) Get(name string) (*v1alpha1.HadoopMapreduce, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hadoopmapreduce"), name)
	}
	return obj.(*v1alpha1.HadoopMapreduce), nil
}
