// This file was automatically generated by lister-gen

package v1alpha1

import (
	v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/apis/example.com/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HadoopYarnLister helps list HadoopYarns.
type HadoopYarnLister interface {
	// List lists all HadoopYarns in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopYarn, err error)
	// HadoopYarns returns an object that can list and get HadoopYarns.
	HadoopYarns(namespace string) HadoopYarnNamespaceLister
	HadoopYarnListerExpansion
}

// hadoopYarnLister implements the HadoopYarnLister interface.
type hadoopYarnLister struct {
	indexer cache.Indexer
}

// NewHadoopYarnLister returns a new HadoopYarnLister.
func NewHadoopYarnLister(indexer cache.Indexer) HadoopYarnLister {
	return &hadoopYarnLister{indexer: indexer}
}

// List lists all HadoopYarns in the indexer.
func (s *hadoopYarnLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopYarn, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopYarn))
	})
	return ret, err
}

// HadoopYarns returns an object that can list and get HadoopYarns.
func (s *hadoopYarnLister) HadoopYarns(namespace string) HadoopYarnNamespaceLister {
	return hadoopYarnNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HadoopYarnNamespaceLister helps list and get HadoopYarns.
type HadoopYarnNamespaceLister interface {
	// List lists all HadoopYarns in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.HadoopYarn, err error)
	// Get retrieves the HadoopYarn from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.HadoopYarn, error)
	HadoopYarnNamespaceListerExpansion
}

// hadoopYarnNamespaceLister implements the HadoopYarnNamespaceLister
// interface.
type hadoopYarnNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HadoopYarns in the indexer for a given namespace.
func (s hadoopYarnNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HadoopYarn, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HadoopYarn))
	})
	return ret, err
}

// Get retrieves the HadoopYarn from the indexer for a given namespace and name.
func (s hadoopYarnNamespaceLister) Get(name string) (*v1alpha1.HadoopYarn, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hadoopyarn"), name)
	}
	return obj.(*v1alpha1.HadoopYarn), nil
}
