// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	example_com_v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/apis/example.com/v1alpha1"
	versioned "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/tangfeixiong/go-to-kubernetes/hadoop-operator/pkg/client/listers/example.com/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HadoopYarnInformer provides access to a shared informer and lister for
// HadoopYarns.
type HadoopYarnInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HadoopYarnLister
}

type hadoopYarnInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHadoopYarnInformer constructs a new informer for HadoopYarn type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHadoopYarnInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHadoopYarnInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHadoopYarnInformer constructs a new informer for HadoopYarn type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHadoopYarnInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().HadoopYarns(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ExampleV1alpha1().HadoopYarns(namespace).Watch(options)
			},
		},
		&example_com_v1alpha1.HadoopYarn{},
		resyncPeriod,
		indexers,
	)
}

func (f *hadoopYarnInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHadoopYarnInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *hadoopYarnInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&example_com_v1alpha1.HadoopYarn{}, f.defaultInformer)
}

func (f *hadoopYarnInformer) Lister() v1alpha1.HadoopYarnLister {
	return v1alpha1.NewHadoopYarnLister(f.Informer().GetIndexer())
}
